
backend:
  name: github
  branch: master
  repo: ActiveLearningStudio/netlify-cms
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'hero'
    label: 'hero'
    folder: 'markdown/home/hero'
    create: true
    fields:
        - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Description', name: 'description', widget: 'text' }
        - { label: 'Gender', name: 'featuredpost', widget: 'boolean' }
        - { label: 'Featured Image', name: 'featuredimage', widget: image }

  - name: 'testonomials'
    label: 'testonomials'
    folder: 'markdown/home/testonomials'
    create: true
    fields:
        - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
        - { label: 'Title', name: 'title', widget: 'string'  }
        - { label: 'Color', name: 'color', widget: 'color' ,enableAlpha: true, allowInput: true  }
        - {label: 'Birthdate',name: 'birthdate',widget: 'date',default: '', format: 'MMM Do YY' }
        - { label: 'Upload file', name: 'tags', widget: 'file' }
        - { label: 'Your Favourite Projects', name: 'favouriteProjects', widget: 'list', default: ["news"]}
        - { label: 'Your Location', name: 'location', widget: 'map'}

  - name: 'contact-us'
    label: 'contact-us'
    folder: 'markdown/home/contact-us'
    create: true
    fields:
        - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
        - { label: 'Title', name: 'title', widget: 'string'  }
        - {label: 'Enter  your age',name: 'your age',widget: 'number',default: '18'}
        - {label: 'Curriki Member', name: 'member', widget: 'boolean', default: true}
        - { label: 'Select your country', name: 'country', widget: 'select' , options: ['Pakistan', 'USA', 'UK']}
        - { label: 'Blog post content', name: 'description', widget: 'markdown' }

          


    