
backend:
  name: github
  branch: master
  repo: ActiveLearningStudio/netlify-cms
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'home page'
    label: 'Home Page'
    files:
      - file: 'markdown/homePage/heroSection.md'
        label: "heroSection"
        name: "heroSection"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "hero-section"}
          - {label: Title, name: title, widget: string}
          - { label: 'Heading One', required: false,   name: 'heading one', widget: string }
          - { label: 'Heading Two', required: false,   name: 'heading two', widget: text }
          - { label: 'Heading Three', required: false,  name: 'heading Three', widget: text }
          - { label: 'Hero Image', required: false,  name: 'hero image', widget: image }
      - file: 'markdown/homePage/forCardSection.md'
        label: "forCardSection"
        name: "forCardSection"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "for-cardsection"}
          - {label: Title, name: title, widget: string}
          - {label: Cards, required: false, name: cards, widget:  object, fields: [{label: Card, required: false, name: card, widget: list, fields: [{ label: 'Card Logo', required: false, name: 'card logo', widget: image },{label: Card Heading One, required: false, name: card heading one, widget: string},{label: Card Heading Two, required: false, name: card heading two, widget: text},{label: Link Name, required: false, name: link name, widget: string},{label: Link Url, required: false, name: link url, widget: string}]}]}
      - file: 'markdown/homePage/freeLearning.md'
        label: "freeLearning"
        name: "freeLearning"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "free-learning"}
          - {label: Title, name: title, widget: string}
          - { label: 'FreeLearning Image', required: false, name: 'freeLearning image', widget: image }
          - { label: 'FreeLearning Heading One', required: false, name: 'freeLearning heading one', widget: text }
          - {label: Platfroms, name: platfroms,required: false, widget: object, fields: [{label: Platfrom, required: false, name: platfrom, widget: list, fields: [{ label: 'Platfrom Logo', required: false, name: 'platfrom logo', widget: image },{label: Platfrom Heading, required: false, name: platfrom heading, widget: markdown}]}]}
          - { label: 'FreeLearning Heading Two',required: false, name: 'freeLearning heading two', widget: string }
          - {label: FreeLearning Btn,required: false, name: freeLearning btn, widget: object, fields: [{ label: 'Btn Text', required: false, name: 'btn text', widget: string },{ label: 'Btn Url', required: false, name: 'btn url', widget: string }]}
      - file: 'markdown/homePage/currikiStats.md'
        label: "CurrikiStats"
        name: "currikiStats"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "curriki-stats"}
          - {label: Title, name: title, widget: string}
          - { label: 'CurrikiStats Heading', required: false, name: 'currikiStats heading', widget: string }
          - { label: 'CurrikiStats description' , required: false, name: 'currikiStats descrip', widget: markdown }
          - {label: Communitys, name: communitys, required: false, widget: object, fields: [{label: Community, required: false, name: community, widget: list, fields: [{ label: 'Community Logo', required: false, name: 'community logo', widget: image },{label: Community Numbers, required: false, name: community navbars, widget: string},{label: Community Names, required: false, name: community names, widget: string}]}]}
          - {label: CurrikiStats Btn, name: currikiStats btn, required: false, widget: object, fields: [{ label: 'CrruikiBtn Text', required: false, name: 'crruikiBtn text', widget: string },{ label: 'CrruikiBtn Url', required: false, name: 'crruikiBtn url', widget: string }]}
      - file: 'markdown/homePage/learningTechnology.md'
        label: "LearningTechnology"
        name: "learningTechnology"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "learning-technology"}
          - {label: Title, name: title, widget: string}
          - { label: 'LearningTechnology Heading',  name: 'learningTechnology heading',  required: false, widget: string }
          - {label: Communitys, name: communitys,  required: false, widget: object, fields: [{label: Community, name: community, required: false, widget: list, fields: [{ label: 'LearningTechnology logos',required: false, name: 'learningTechnology logos', widget: image }]}]}
      - file: 'markdown/homePage/customersSay.md'
        label: "CustomersSay"
        name: "customersSay"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "customers-say" }
          - {label: Title, name: title, widget: string}
          - { label: 'CustomersSay Heading',  name: 'customersSay heading',  required: false, widget: string }
          - {label: CustomersSay Slider, name: customersSay slider,  required: false, widget: object, fields: [{label: Slider, name: slider, required: false, widget: list, fields: [{ label: 'Slider Descrip',  name: 'slider descrip',  required: false, widget: markdown },{ label: 'User Image',required: false, name: 'user image', widget: image },{ label: 'User Name',required: false, name: 'user name', widget: string }]}]}
      - file: 'markdown/homePage/startCurriki.md'
        label: "StartCurriki"
        name: "startCurriki"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "start-curriki" }
          - {label: Title, name: title, widget: string}
          - { label: 'startCurriki Heading',  name: 'startCurriki heading',  required: false, widget: string }
          - {label: startDemos, name: startDemos,  required: false, widget: object, fields: [{label: Demo, name: demo, required: false, widget: list, fields: [{ label: 'Demo Title',  name: 'demo title',  required: false, widget: string },{label: Demos Btn, name: demos btn, required: false, widget: object, fields: [{ label: 'DemoBtn Text', required: false, name: 'demoBtn text', widget: string },{ label: 'DemoBtn Url', required: false, name: 'demoBtn url', widget: string }]}]}]}
      - file: 'markdown/homePage/contactUs.md'
        label: "ContactUs"
        name: "contactUs"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-us"}
          - {label: Title, name: title, widget: string}
          - { label: 'ContactHeading One', required: false, name: 'contactheading one', widget: string }
          - { label: 'ContactHeading Two', required: false,   name: 'contactheading two', widget: text }
          - { label: 'ContactUs Btn', required: false,  name: 'contactUs btn', widget: string }
          - { label: 'ContactUs Image', required: false,  name: 'contactUs image', widget: image }

  - name: 'layout'
    label: 'Layout'
    files:
      - file: 'markdown/layout/topnave.md'
        label: "Navigation Bar"
        name: "topnav"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "top-navbar"}
          - {label: Title, name: title, widget: string}
          - { label: 'Top Logo', name: 'top logo', widget: image }
          - {label: Add Links, name: add links, widget: object, fields: [{label: Links, name: links, widget: list, fields: [{label: Link Name, name: link name, widget: string}, {label: URl, required: false, name: url, widget: string},{label: Links, required: false, name: links, widget: list, fields: [{label: Link Name, required: false, name: link name, widget: string}, {label: URl, required: false, name: url, widget: string}]}]}]}
      - file: 'markdown/layout/footer.md'
        label: "Footer"
        name: "footer"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "footer-area"}
          - {label: Title, name: title, widget: string}
          - { label: 'Footer Logo',  required: false, name: 'footer logo', widget: image }
          - {label: Pages,  required: false, name: pages, widget: object, fields: [{label: page, name: page, widget: list, fields: [{label: PageName, name: pagename, widget: string}, {label: Page URl, name: pageurl, widget: string}]}]}
          - {label: Social Media Icon,  required: false, name: social media Icon, widget: object, fields: [{label: Icons, name: icons, widget: list, fields: [{label: SMIcon, name: SMIcon, widget: image}, {label: Icon URl, name: icon url, widget: string}]}]}
          - {label: Powered By, name: powered by, widget: markdown}

  - name: "comingsoon page"
    label: "ComingSoon page"
    files:
      - file: "markdown/comingsoonpage/comingsoon.md"
        label: "ComingSoon"
        name: "comingsoon"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "coming-soon"}
          - {label:  Title, name: title, widget: string}
          - { label: 'Coming Image', name: 'coming image', widget: image }
          - {label:  Description, name: description, widget: markdown}



