
backend:
  name: github
  branch: master
  repo: ActiveLearningStudio/netlify-cms
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'layout'
    label: 'Layout'
    files:
      - file: 'markdown/layout/topnave.md'
        label: "Navigation Bar"
        name: "topnav"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "top-navbar"}
          - {label: Title, name: title, widget: string}
          - { label: 'Top Logo', name: 'top logo', widget: image }
          - {label: Add Links, name: add links, widget: object, fields: [{label: Links, name: links, widget: list, fields: [{label: Link Name, name: link name, widget: string}, {label: URl, name: url, widget: string}]}]}
      - file: 'markdown/layout/footer.md'
        label: "Footer"
        name: "footer"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "footer-area"}
          - {label: Title, name: title, widget: string}
          - {label: Pages, name: pages, widget: object, fields: [{label: page, name: page, widget: list, fields: [{label: PageName, name: pagename, widget: string}, {label: Page URl, name: pageurl, widget: string}]}]}
          - { label: 'Footer Logo', name: 'footer logo', widget: image }
          - {label: Powered By, name: powered by, widget: string}

  - name: "comingsoon page"
    label: "ComingSoon page"
    files:
      - file: "markdown/comingsoonpage/comingsoon.md"
        label: "ComingSoon"
        name: "comingsoon"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "coming-soon"}
          - {label:  Title, name: title, widget: string}
          - { label: 'Coming Image', name: 'coming image', widget: image }            
          - {label:  Description, name: description, widget: markdown}   

    
       

          


    